[package]
name = "utils"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# colored_error_messages
termcolor = { version = "1.1" }
atty = "0.2"
clap = "~3.0.0-beta.2"
