[package]
name = "utils"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atty = "0.2"
clap = "~3.0.0-beta.2"

derive_more = "0.99"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1"

# colored_error_messages
termcolor = { version = "1.1" }

thiserror = "1.0.25"

num-traits = "0.2"

[dev-dependencies]
test-case = "1.1.0"
