[package]
name = "weather_app"
version = "0.1.0"
authors = ["gcfbn <bmekarski@interia.pl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
restson = "^0.7"
serde = "^1.0"
serde_derive = "^1.0"